/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aavalos' at '9/18/16 2:01 AM' with Gradle 2.13
 *
 * @author aavalos, @date 9/18/16 2:01 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
